/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pusdigg;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dppra
 */
public class kategori extends javax.swing.JPanel {

    /**
     * Creates new form kategori
     */
    Connection conn = null;
    ResultSet rs =null;
    PreparedStatement pst = null;
    
    private DefaultTableModel model;
    private String sql;
    
    String id = session.getU_id();
    String usernamee = session.getU_username();
    public kategori() {
        initComponents();
        id_user.setText("SELAMAT DATANG "+id);
        username.setText("ANDA LOGIN SEBAGAI "+usernamee);

        conn = koneksi.koneksi.koneksiDB();

        model = new DefaultTableModel();
        jTable1.setModel(model);

        // Tambahkan kolom tabel
        model.addColumn("Kategori_Id");
        model.addColumn("Name_Kategori");
        model.addColumn("Created_At");

        // Sembunyikan kolom ID
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);

        getData();
    }
    
void getData() {
    model.setRowCount(0);

    try {
        String sql = "SELECT * FROM kategori";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        while (rs.next()) {
            Object[] obj = new Object[3];
            obj[0] = rs.getInt("Kategori_Id");
            obj[1] = rs.getString("Name_Kategori");
            obj[2] = rs.getDate("Created_At");
            model.addRow(obj);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

 

   void pilihData() {
    int i = jTable1.getSelectedRow();
    nama.setText(model.getValueAt(i, 1).toString());
}


 
    void bersih() {
        nama.setText("");
        jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Cari = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        id_user = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1860, 1080));
        setPreferredSize(new java.awt.Dimension(1860, 1080));

        jPanel1.setBackground(new java.awt.Color(197, 216, 157));
        jPanel1.setMinimumSize(new java.awt.Dimension(1860, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1860, 1080));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 490, 70));

        jButton1.setText(".");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 700, 220, 60));

        jButton2.setText(".");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 790, 220, 70));

        jButton3.setText(".");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 700, 210, 60));

        jButton4.setText(".");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 790, 200, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 860, 490));

        jLabel1.setText("Nama Kategori");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 28, -1, -1));

        Cari.setText(".");
        Cari.setContentAreaFilled(false);
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        jPanel1.add(Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 170, 220, 50));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 180, 530, 30));

        id_user.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        id_user.setForeground(new java.awt.Color(255, 255, 255));
        id_user.setText("Id_user");
        jPanel1.add(id_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 60, 360, -1));

        username.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 100, 360, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1860/Kategori dan jenis buku.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getData();
        bersih();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        pilihData();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    try {
        String sql = "INSERT INTO kategori (name_kategori, created_by, update_by) VALUES (?, ?, ?)";
        pst = conn.prepareStatement(sql);
        pst.setString(1, nama.getText());
        pst.setString(2, session.getU_id());
        pst.setString(3, session.getU_id());
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

        getData();
        bersih();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 
    int i = jTable1.getSelectedRow();
    int id = Integer.parseInt(model.getValueAt(i, 0).toString());

    try {
        String sql = "UPDATE kategori SET Name_Kategori=?, update_by=? WHERE kategori_id=?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, nama.getText());
        pst.setString(2, session.getU_id());
        pst.setInt(3, id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Update sukses");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

    getData();
    bersih();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    int i = jTable1.getSelectedRow();
    int id = Integer.parseInt(model.getValueAt(i, 0).toString());

    int a = JOptionPane.showConfirmDialog(null,
            "Yakin ingin menghapus?",
            "Delete",
            JOptionPane.YES_NO_OPTION);

    if (a == JOptionPane.YES_OPTION) {
        try {
            String sql = "DELETE FROM kategori WHERE kategori_id=?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    getData();
    bersih();


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0); // reset tabel

    try {
        String keyword = jTextField1.getText();
        String sql = "SELECT * FROM kategori WHERE Name_Kategori LIKE ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, "%" + keyword + "%");
        rs = pst.executeQuery();

        while (rs.next()) {
            Object[] obj = new Object[3];
            obj[0] = rs.getInt("Kategori_Id");
            obj[1] = rs.getString("Name_Kategori");
            obj[2] = rs.getDate("Created_At");
            model.addRow(obj);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_CariActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JLabel id_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
