/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pusdigg;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dppra
 */
public class registrasi extends javax.swing.JFrame {

    /**
     * Creates new form registrasi
     */
     Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public registrasi() {
        setLocationRelativeTo(this);
          conn = koneksi.koneksi.koneksiDB();
        initComponents();
    }
    
     void bersih() {
       usernameTxt.setText("");
       jPasswordField1.setText("");
       namalengkap.setText("");
       telp.setText("");
       email.setText("");
       jTextArea1.setText("");
       cmb_role.setSelectedItem("");
       cmb_status.setSelectedItem("");
       
   }
     
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameTxt = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        namalengkap = new javax.swing.JTextField();
        cmb_role = new javax.swing.JComboBox<String>();
        telp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmb_status = new javax.swing.JComboBox<String>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 370, 28));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, 360, 27));

        namalengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namalengkapActionPerformed(evt);
            }
        });
        jPanel1.add(namalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 630, 360, 28));

        cmb_role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "user" }));
        jPanel1.add(cmb_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 760, 340, 28));

        telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telpActionPerformed(evt);
            }
        });
        jPanel1.add(telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 370, 360, 28));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 620, 380, 60));

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "guru", "siswa", "pengunjung" }));
        jPanel1.add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 510, 350, 27));

        jButton1.setText("DF");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 890, 434, 32));

        jLabel9.setBackground(new java.awt.Color(255, 255, 51));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Password masksimal 8 karakter");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 560, -1, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 750, 360, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1920/Registrasi.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1923, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void namalengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namalengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namalengkapActionPerformed

    private void telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // 🔴 VALIDASI FIELD WAJIB (SESUI DB)
if (usernameTxt.getText().trim().isEmpty() ||
    jPasswordField1.getPassword().length == 0 ||
    namalengkap.getText().trim().isEmpty() ||
    telp.getText().trim().isEmpty() ||
    email.getText().trim().isEmpty() ||
    cmb_role.getSelectedItem() == null ||
    cmb_status.getSelectedItem() == null) {

    JOptionPane.showMessageDialog(
        null,
        "NISN/NIP/NIK, Password, Nama Lengkap, Telp, Email, Role, dan Status WAJIB diisi!",
        "Peringatan",
        JOptionPane.WARNING_MESSAGE
    );
    return; // ⛔ STOP SIMPAN
}     
        
          try{
           String sql = "insert into user (nomor,password,fullname,role,telp,email,status,alamat)values(?,?,?,?,?,?,?,?)";
           pst = conn.prepareStatement(sql);
           pst.setString(1, usernameTxt.getText());
           pst.setString(2, jPasswordField1.getText());
           pst.setString(3, namalengkap.getText());
           pst.setString(4, (String) cmb_role.getItemAt(cmb_role.getSelectedIndex()));
           pst.setString(5, telp.getText());
           pst.setString(6, email.getText());
           pst.setString(7, (String) cmb_status.getItemAt(cmb_status.getSelectedIndex()));
           pst.setString(8, jTextArea1.getText());
           pst.execute();
           JOptionPane.showMessageDialog(null, "Berhasil Melakukan Registrasi");
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
       }
      bersih();
      
        login lgn = new login();
        lgn.setVisible(true);
        this.setVisible(false);
        this.dispose();
             
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_role;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField namalengkap;
    private javax.swing.JTextField telp;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
