/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pusdigg;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pusdigg.kategori;
import pusdigg.buku;
import pusdigg.riwayat_transaksi_admin;
import pusdigg.transaksi_admin;
import pusdigg.dashboard_admin;
import pusdigg.user;

/**
 * Form utama navigasi untuk pengguna dengan role <b>Admin</b>.
 * <p>
 * Kelas ini merupakan JFrame utama yang menampilkan sidebar navigasi di sisi kiri
 * dan area konten utama (CardLayout) di sisi kanan. Setiap tombol pada sidebar
 * akan mengganti panel yang ditampilkan di area konten menggunakan {@link CardLayout}.
 * </p>
 *
 * <p>Modul yang dapat diakses admin melalui sidebar ini:</p>
 * <ul>
 *   <li>Dashboard Admin</li>
 *   <li>Manajemen User</li>
 *   <li>Manajemen Kategori Buku</li>
 *   <li>Manajemen Buku</li>
 *   <li>Manajemen Item Buku (Kode Buku)</li>
 *   <li>Transaksi Peminjaman</li>
 *   <li>Riwayat Transaksi</li>
 *   <li>Logout</li>
 * </ul>
 *
 * @author dppra
 * @version 1.0
 * @since 2026
 */
public class sidebar_admin extends javax.swing.JFrame {

    dashboard_admin a = new dashboard_admin();
    kategori b = new kategori();
    buku c = new buku();
    transaksi_admin d = new transaksi_admin();
    riwayat_transaksi_admin e = new riwayat_transaksi_admin();
    user f = new user();
    itembuku g = new itembuku();

    /**
     * Membuat form sidebar_admin dan menginisialisasi semua panel navigasi.
     * <p>
     * Semua modul (dashboard, buku, kategori, dll.) diregistrasi ke dalam
     * {@link CardLayout} saat konstruktor dipanggil. Form akan ditampilkan
     * dalam mode layar penuh (maximized).
     * </p>
     */
    public sidebar_admin() {
        initComponents();
        main.setLayout(new CardLayout());
        main.add(a, "dashboard_admin");
        main.add(b, "kategori");
        main.add(c, "buku");
        main.add(d, "transaksi_admin");
        main.add(e, "riwayat_transaksi_admin");
        main.add(f, "user");
        main.add(g, "itembuku");

        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "sidebar_admin");

        javax.swing.JButton[] menuButtons = {jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton8, jButton9};
        for (javax.swing.JButton btn : menuButtons) {
            stylingTeksMurni(btn);
            addTextHoverEffect(btn);
        }
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * Mengatur styling tombol menu agar tampil seperti teks biasa tanpa border.
     * <p>
     * Menghilangkan background, border, dan efek fokus pada tombol sehingga
     * tampilan lebih bersih sebagai menu navigasi.
     * </p>
     *
     * @param button Tombol {@link javax.swing.JButton} yang akan diubah tampilannya
     */
    private void stylingTeksMurni(javax.swing.JButton button) {
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setFocusPainted(false);
        button.setOpaque(false);
        button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    }

    /**
     * Menambahkan efek hover (perubahan warna) pada tombol menu navigasi.
     * <p>
     * Warna teks akan berubah menjadi merah-muda ({@code #FF3366}) saat
     * kursor berada di atas tombol, dan kembali ke warna hitam saat kursor pergi.
     * </p>
     *
     * @param button Tombol {@link javax.swing.JButton} yang akan diberi efek hover
     */
    private void addTextHoverEffect(javax.swing.JButton button) {
        java.awt.Color warnaAsli = java.awt.Color.BLACK;
        java.awt.Color warnaHover = new java.awt.Color(255, 51, 102);

        button.setForeground(warnaAsli);
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button.setForeground(warnaHover);
                button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button.setForeground(warnaAsli);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        main = new javax.swing.JLayeredPane();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(102, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("D");
        jButton1.setAlignmentY(0.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 50, 30));

        jButton3.setText("B");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 50, -1));

        jButton2.setText("k");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 50, 30));

        jButton4.setText("T");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 50, 40));

        jButton5.setText("R");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 770, 50, 40));

        jButton6.setText("U");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 50, 40));

        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 970, -1, -1));

        jButton9.setText("Kode");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1920/side.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 1080));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        main.setBackground(new java.awt.Color(197, 216, 157));
        main.setMinimumSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "itembuku");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null,
            "Apakah Anda yakin ingin logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            session.logout();
            this.dispose();
            login Login = new login();
            Login.setVisible(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "user");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "riwayat_transaksi_admin");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "transaksi_admin");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "kategori");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "buku");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout cl = (CardLayout) main.getLayout();
        cl.show(main, "dashboard_admin");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Titik masuk utama untuk menjalankan form sidebar_admin secara langsung.
     * @param args argumen command line (tidak digunakan)
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sidebar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sidebar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sidebar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sidebar_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sidebar_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane main;
    // End of variables declaration//GEN-END:variables
}
