/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pusdigg;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.prompt.PromptSupport;
/**
 *
 * @author dppra
 *  * Form untuk manajemen data pengguna (CRUD User) oleh Admin.
 */
public class user extends javax.swing.JPanel {

    /**
     * Creates new form user
     */
     Connection conn = null;
    ResultSet rs =null;
    PreparedStatement pst = null;
    
    private DefaultTableModel model;
    private String sql;
    
    String id = session.getU_id();
    String usernamee = session.getU_username();
    public user() {
        initComponents();
        
        id_user.setText(id);
        username.setText(usernamee);
        conn = koneksi.koneksi.koneksiDB();

        // PLACEHOLDER
        PromptSupport.setPrompt("Masukkan NISN/NIP/NIK", jTextField5);
        
        model = new DefaultTableModel();
        jTable1.setModel(model);

        // Tambahkan kolom tabel
        model.addColumn("user_id");
        model.addColumn("NISN/NIP/NIK");
        model.addColumn("Password");
        model.addColumn("Nama Lengkap");
        model.addColumn("Role");
        model.addColumn("Telp");
        model.addColumn("Email");
        model.addColumn("Status");
        model.addColumn("Alamat"); 
        
        // Sembunyikan kolom ID
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setWidth(0);
        getData();
    }
    
    
    // Tambah di atas method getData():
/**
 * Mengambil semua data user dari database dan menampilkannya ke JTable.
 */
    void getData() {
    model.setRowCount(0);

    try {
        String sql = "SELECT * FROM user";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        while (rs.next()) {
            Object[] obj = new Object[9];
            obj[0] = rs.getString("user_id");
            obj[1] = rs.getString("nomor");
            obj[2] = rs.getString("password");
            obj[3] = rs.getString("fullname");
            obj[4] = rs.getString("role");
            obj[5] = rs.getString("telp");
            obj[6] = rs.getString("email");
            obj[7] = rs.getString("status");
            obj[8] = rs.getString("alamat");
          
            model.addRow(obj);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

 

  void pilihData() {
    int i = jTable1.getSelectedRow();

    txt_username.setText(model.getValueAt(i, 1).toString());
    txt_password.setText(model.getValueAt(i, 2).toString());
    txt_namalengkap.setText(model.getValueAt(i, 3).toString());
    cmb_role.setSelectedItem(model.getValueAt(i, 4).toString());
    txt_telp.setText(model.getValueAt(i, 5).toString());
    txt_email.setText(model.getValueAt(i, 6).toString());
    cmb_status.setSelectedItem(model.getValueAt(i, 7).toString());
    jTextArea1.setText(model.getValueAt(i, 8).toString());
}


 
    void bersih() {
    txt_username.setText("");
    txt_password.setText("");
    txt_namalengkap.setText("");
    txt_telp.setText("");
    jTextArea1.setText("");
    jTextField5.setText("");
    cmb_role.setSelectedItem(null);   // kembali ke item pertama
    cmb_status.setSelectedItem(null);
    txt_email.setText("");
    jTable1.clearSelection();       // hilangkan seleksi tabel (opsional)
}

       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_namalengkap = new javax.swing.JTextField();
        cmb_role = new javax.swing.JComboBox<String>();
        txt_telp = new javax.swing.JTextField();
        cmb_status = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        id_user = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 450, 30));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 450, 30));
        add(txt_namalengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 450, 30));

        cmb_role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "user" }));
        add(cmb_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 450, 40));
        add(txt_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 450, 30));

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "guru", "siswa", "pengunjung" }));
        add(cmb_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 692, 440, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 786, 450, 50));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setText(".");
        jButton1.setToolTipText("");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 690, 180, 50));

        jButton2.setText(".");
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 690, 190, 60));

        jButton3.setText(".");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 690, 200, 60));

        jButton4.setText(".");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 690, 190, 60));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 1060, 380));
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 510, 30));

        jButton5.setText(".");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 180, 260, 30));

        id_user.setText("jLabel8");
        add(id_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 60, -1, -1));

        username.setText("jLabel8");
        add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 120, -1, -1));
        add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 890, 470, 33));

        jLabel9.setText("aaaaaaaaaa");
        jLabel9.setMaximumSize(new java.awt.Dimension(1860, 1080));
        jLabel9.setMinimumSize(new java.awt.Dimension(1860, 1080));
        jLabel9.setPreferredSize(new java.awt.Dimension(1860, 1080));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1860, 1080, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1860/Manajemen Pengguna.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try{
           String sql = "insert into user (nomor,password,fullname,role,telp,email,status,alamat ,created_by, update_by)values(?,?,?,?,?,?,?,?,?,?)";
           pst = conn.prepareStatement(sql);
           pst.setString(1, txt_username.getText());
           pst.setString(2, txt_password.getText());
           pst.setString(3, txt_namalengkap.getText());
           pst.setString(4, (String) cmb_role.getItemAt(cmb_role.getSelectedIndex()));
           pst.setString(5, txt_telp.getText());
           pst.setString(6, txt_email.getText());
           pst.setString(7, (String) cmb_status.getItemAt(cmb_status.getSelectedIndex()));
           pst.setString(8, jTextArea1.getText());
           pst.setString(9, session.getU_id());
           pst.setString(10, session.getU_id());
           pst.execute();
           JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
       } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);
       }
      bersih();
       
    
    getData();
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        bersih();
        getData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    int i = jTable1.getSelectedRow();
    int id = Integer.parseInt(model.getValueAt(i, 0).toString());

    try {
        String sql = "UPDATE user SET nomor=?, password=?, fullname=?, role=?, status=?, alamat=?, telp=?, email=?, update_by=? WHERE user_id=?";
        pst = conn.prepareStatement(sql);

        pst.setString(1, txt_username.getText());
        pst.setString(2, txt_password.getText());
        pst.setString(3, txt_namalengkap.getText());

        // ✅ ambil nilai JComboBox
        pst.setString(4, cmb_role.getSelectedItem().toString());
        pst.setString(5, cmb_status.getSelectedItem().toString());

        pst.setString(6, jTextArea1.getText());     // alamat
        pst.setString(7, txt_telp.getText());       // telp
        pst.setString(8, txt_email.getText());       // email
        pst.setString(9, session.getU_id());        // update_by
        pst.setInt(10, id);                          // user_id

        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Update sukses");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }


    getData();
    bersih();
         

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        pilihData();
    }//GEN-LAST:event_jTable1MouseClicked

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int i = jTable1.getSelectedRow();
    int id = Integer.parseInt(model.getValueAt(i, 0).toString());

    int a = JOptionPane.showConfirmDialog(null,
            "Yakin ingin menghapus?",
            "Delete",
            JOptionPane.YES_NO_OPTION);

    if (a == JOptionPane.YES_OPTION) {
        try {
            String sql = "DELETE FROM user WHERE user_id=?";
            pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    getData();
    bersih();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        model.setRowCount(0); // reset tabel

    try {
        String keyword = jTextField5.getText();
        String sql = "SELECT * FROM user WHERE nomor LIKE ?";
        pst = conn.prepareStatement(sql);
        pst.setString(1, "%" + keyword + "%");
        rs = pst.executeQuery();

        while (rs.next()) {
            Object[] obj = new Object[8];
            obj[0] = rs.getString("user_id");
            obj[1] = rs.getString("nomor");
            obj[2] = rs.getString("password");
            obj[3] = rs.getString("fullname");
            obj[4] = rs.getString("role");
            obj[5] = rs.getString("telp");
            obj[6] = rs.getString("status");
            obj[7] = rs.getString("alamat");
            model.addRow(obj);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_role;
    private javax.swing.JComboBox<String> cmb_status;
    private javax.swing.JLabel id_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_namalengkap;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_telp;
    private javax.swing.JTextField txt_username;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
